// lab01/frontend/src/components/TodoList.jsx
import React, { useEffect, useState } from 'react'
import axios from "axios";
import styles from './TodoList.module.css'

const TodoList = () => {
    const [keySearch, setkeySearch] = useState('')
    const [todos, setTodos] = useState([{content: "Abcxyz", finished: false}])
    const axiosInstance = axios.create({
        baseURL: window.location.origin + ":82",
    });
    axiosInstance.defaults.headers.common = {
        ...axiosInstance.defaults.headers.common,
        Accept: "application/json",
        "Content-Type": "application/json",
    };

    useEffect(() => {
        const getData = async () => {
            try {
                let res = await axiosInstance.get("/api/tasks");
                setTodos(res.data);
            } catch (error) {
                console.log(error);
            }
        };

        return () => {
            getData()

        }
    }, [todos,axiosInstance])



    function addTodo() {
        let newTask = {
            content: keySearch.trim(),
        };
        axiosInstance
            .post("/api/tasks", newTask)
            .then((res) => {
                setTodos([...todos, res.data]);
            })
            .catch((e) => {
                console.log(e);
            });
    }
    const onFinished = ($event, ele) => {
        console.log($event)
        let value = !ele.finished;
        let toDoItem = { ...ele, finished: !ele.finished };
        axiosInstance
            .put("/api/tasks", toDoItem)
            .then((res) => {
                console.log(res)
                ele.finished = value;
            })
            .catch((e) => {
                console.log(e);
            });
    }

    return (
        <>
            <div className={`${styles.wrapper}`}>
                <h1>TODO LIST</h1>
                <input
                    type="text"
                    className={`${styles.inputSearch}`}
                    onChange={($event) => setkeySearch($event.target.value)}
                    placeholder="Input to do"
                    onKeyDown={($event) => $event.code === "Enter" && addTodo()}
                />
    
                {
                    todos && todos.map((todo, id) => (
                        <li key={{ id }}>
                            <input
                                type="checkbox"
                                className={`${styles.inputCheckbox}`}
                                checked={todo.finished}
                                onChange={($event) => onFinished($event, todo)} />
                            {todo.content}
                        </li>
                    ))
                }
                <p>
                    Completed to do: <b>{todos && todos.filter((todo) => todo.completed).length}</b>
                </p>
            </div>
        </>
    )
}


export default TodoList

// lab01/client/src/components/TodoList.vue
<template>
  <h1>TODO LIST</h1>
  <input
    type="text"
    v-model="todoSearch"
    placeholder="Nhập việc cần làm"
    @keyup.enter="addTodo"
  />
  <ul>
    <li v-for="todo in todos" :key="todo.id">
      <input
        type="checkbox"
        :checked="todo.finished"
        @change="onFinished($event, todo)"
      />
      {{ todo.content }}
    </li>
  </ul>
  <p>
    Số công việc đã hoàn thành: <b>{{ numberOfCompletedTodos }}</b>
  </p>
</template>

<script>
import { onMounted, computed, ref, watch } from "vue";
import axios from "axios";

export default {
  setup() {
    const todoSearch = ref("");
    const todos = ref([]);
    const axiosInstance = axios.create({
      baseURL: "http://localhost:8001",
    });

    axiosInstance.defaults.headers.common = {
      ...axiosInstance.defaults.headers.common,
      Accept: "application/json",
      "Content-Type": "application/json",
    };

    const numberOfCompletedTodos = computed(
      () => todos.value.filter((todo) => todo.completed).length
    );

    const getData = async () => {
      try {
        let res = await axiosInstance.get("/api/tasks");
        todos.value = res.data;
      } catch (error) {
        console.log(error);
      }
    };

    function addTodo() {
      let newTask = {
        content: todoSearch.value.trim(),
      };

      axiosInstance
        .post("/api/tasks", newTask)
        .then((res) => {
          todos.value.push(res.data);
        })
        .catch((e) => {
          console.log(e);
        });
    }

    const onFinished = (e, ele) => {
      console.log(e.target.value, ele.finished);
      let value = !ele.finished;
      let fakeTodo = { ...ele, finished: !ele.finished };
      axiosInstance
        .put("/api/tasks", fakeTodo)
        .then((res) => {
          ele.finished = value;
        })
        .catch((e) => {
          console.log(e);
        });
      //   try {
      //
      //   } catch (error) {
      //     console.log(error);
      //   }
    };

    onMounted(() => {
      getData();
    });

    watch(
      todos,
      (newValue) => {
        console.log(`Length: ${newValue.length}`);
      },
      { deep: true }
    );

    return {
      todoSearch,
      todos,
      addTodo,
      onFinished,
      numberOfCompletedTodos,
    };
  },
};
</script>
